name: Test

on:
  pull_request:
    branches: [ main, master ]
    
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      
    - name: Run tests
      run: | 
        cd ..
        npm i
        npm test
    
  
    
