name: Test

on:
  push:
    branches: [ main ]
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://a924-192-38-10-18.ngrok.io'
        method: 'GET'
