name: Test

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://8a37-130-225-198-189.ngrok.io'
        method: 'GET'
