name: Test

on:
  pull_request:
    branches: [ main, master ]
    
jobs:
  run_tests:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      
    - name: Install dependencies
      run: npm i
      
    - name: Run tests
      id: test-results
      uses: ./test/run-tests-action

    - name: Log test results
      run: echo ${{ steps.test-results.outputs.results }}
  
    
