name: Test

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
    
jobs:

  wait_for_response:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for response
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost:3000/'
        responseCode: '200' 
        timeout: 20000
        interval: 500

  run_tests:
    needs: wait_for_response
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      
    - name: Install dependencies
      run: npm i
      
    - name: Run tests
      id: test-results
      uses: ./.github/actions/run-tests-action

    - name: Log test results
      run: echo ${{ steps.test-results.outputs.results }}
  
    
