name: Test

on:
  push:
    branches: [ main ]
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://gorest.co.in/public/v2/users'
        method: 'GET'
