name: Test

on:
  push:
    branches: [ main ]
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://localhost:3000'
        method: 'POST'
